mysql:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: abc123
    MYSQL_DATABASE: polmaker
  expose:
    - 3306
  volumes:
    - /var/lib/mysql
web:
  build: .
  restart: always
  ports:
    - 8000:80
  volumes:
    - ./:/usr/src/app/
  links:
    - mysql
